//Series not found or uncertain of image call #:

{
				id: 'cs4',
				type:'Septuagint Text (Greek)',
				category: 'sources',
				title: 'The Septuagint',
				subtitle: 'The Greek translation of the Old Testament gains new life in the polyglots',
				image: 'Folio Inc. 5966, f. something',
				src: '', //inc_7763?
				metadata: '',
				creator: '',
				textTitle: '[Psalterium Graeco-Latinum cum canticis].',
				place: 'Milan, Italy',
				year: '1481',
				narrative: 'Centuries before the birth of Christ, Greek-speaking Jews living in Egypt created a Greek translation of the Old Testament called the Septuagint, so-called because around 70 (Septuagint is the Latin word for 70) scholars produced it. During the Middle Ages, the Septuagint was relatively unknown in western Europe, where Jerome’s Vulgate translation dominated. Interest in learning and using Greek in religious studies grew throughout the 14th and 15th centuries, especially after the fall of Constantinople to the Ottoman Turks in 1453. Thereafter, Biblical material in Greek began to appear in print, beginning with the psalter pictured here. Inspired by this, Cisneros borrowed Septuagint manuscrips from the Vatican to produce the first printed edition of the entire Septuagint Old Testament in his polyglot.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=400646',
				otherAuthor: 'O’Connell, S.',
				otherTitle: 'From Most Ancient Sources: The Nature and Text-Critical Use of the Greek Old Testament Text of the Complutensian Polyglot Bible.',
				otherBib: 'Fribourg/Göttingen: Vandenhoeck and Ruprecht, 2006.',

			},

{
				id: 'cs5',
				type: 'Hebrew Text',
				category: 'sources',
				title: 'Making Hebrew Type',
				subtitle: 'Letter-founders create new typefaces for polyglots',
				image: 'Case Wing Z 40535 .156, sig. B',
				src:'', ///public/resampled/wing_zp_535_m4677_pg_60_61.jpg
				metadata: '',
				creator: 'Congregatio de Propaganda Fide',
				textTitle: 'Alphabeta varia',
				place: 'Rome, Italy',
				year: '1630',
				narrative: 'Many of the languages that appear in polyglots had rarely, if ever, been printed before. This forced early polyglot scholars to find printers skilled enough to make new print types from scratch, often using manuscript sources. Arnao Gúillen de Brocar, the printer of the Complutensian polyglot, developed six new type founts for the work using the manuscripts Cisneros had collected. A century later, the Catholic church sought to make it easier to print in these languages by circulating print specimens taken from particular sources, such as the one pictured here, which printers throughout Europe could use to make their own types.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=286133',
					otherAuthor: 'Hall, Basil.',
					otherTitle: 'The Great Polyglot Bibles.',
					otherBib: 'Publication number 124 of the Book Club of California. San Francisco: Published for its members by the Book Club of California, 1966.',
				},
{
						id: 'ct2',
						type: 'Vulgate',
						category: 'translations',
						title: 'Calvary on the page',
						subtitle: 'Printers use page layout to protect the authority of the Vulgate',
						image: 'Wing oversize ZP 5465 .P7013 from Plantin Polyglot',
						src:'', //no matching imagery for those call#s
						metadata: '',
						creator: 'Christopher Plantin, printer',
						textTitle: 'Plantin Polyglot',
						place: 'Antwerp, Belgium',
						year: '1571',
						narrative: 'Not everyone was excited about polyglots. Many scholars and ecclesiastical leaders argued that a polyglot edition would ruin Scripture, since it would allow the language of murderers (Jews) and heretics (Greeks) to distract readers from the essential Latin text. The Complutensian scholars refused to leave out these original languages, but placed the Vulgate in the very center of the page, with the Hebrew and Greek alongside. They described it as a representation of the Crucifixion, with Christ flanked by thieves on either side. As the image shows, the Plantin polyglot takes the same visual approach in order to appease the Catholic church. Due to its Protestant origin, the London Polyglot did not bother with this, giving more prominence to the other original languages.',
						link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=234961',
						otherAuthor: 'Fernández Marcos, Natalio. “The First Polyglot Bible.” ',
						otherTitle: 'In The Text of the Hebrew Bible and Its Editions: Studies in Celebration of the Fifth Centennial of the Complutensian Polyglot. Supplements to the Textual History of the Bible 1.',
						otherBib: 'Leiden: Brill, 2014, 3-18.',
					},

					{
					id: 'at2',
					type: 'Latin Vulgate',
					category: 'translations',
					title: 'Royal Patronage',
					subtitle: 'Polyglots as signs of political power',
					image: 'Wing oversize ZP 5465 .P7013, frontispiece',
					src:'', //again no zp 5465...
					metadata: '',
					creator: 'Artist? – Ask Walter Melion',
					textTitle: '',
					place: 'Antwerp, Belgium',
					year: '1571',
					narrative: 'i.	We should be talking about patronage somewhere, and we could use that spectacular frontispiece of Hispania from this edition to show Philip II’s involvement in the project as a way of contributing to the Counter Reform. This is where Reed’s comment about “the Counter-Reformation in folio” should come in. ii.	We could also mention Plantin’s political and economic motivations here, or the fact that the majority of the scholars who worked on the project were actually Protestants.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=234961',
					},
